### PR TITLE
feat: add api blueprint cheatsheet

### PR DESCRIPTION
**Pull request by abtris**

### CODE REVIEW

**Comment by abtris** [comment]
[API Blueprint Cheat Sheet](https://trello.com/c/NMlMJp3O/1-api-blueprint-cheat-sheet)

**Comment by nadade** [comment]
I polished the language but it doesn't seem to me like a cheat sheet here, I'd go with something more brief and to the point...

**Comment by nadade** [comment]
@abtris could you pls add me as collaborator? I cannot seem to be able to push my changes in your branch (extra commit)

**Comment by abtris** [comment]
@nadade fixed

**Pull request merged**
